version: "3.9"
services:
  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: oteleport0000
      MINIO_ROOT_PASSWORD: oteleport0000
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"
    restart: always

volumes:
  minio:

networks:
  default:
    driver: bridge
