name: Test
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.23"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: "3.37"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.28.0
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod tidy

      - name: setup test environment
        run: task local:setup

      - name: Build & Test
        run: |
          go test -race ./... -timeout 30s
